In [ ]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
#Here difflib library helps to find the closest match to the user input
#cosine_similarity hepls to find the similarity score to the user input movie.

In [ ]:
# loading the dataset from the csv file to a pandas Dataframe.
movies_dataset = pd.read_csv('/content/movies.csv')


In [ ]:
movies_dataset.shape

(4803, 24)

In [ ]:
# printing thr first 5 rows of the Dataframe.
movies_dataset.head()


index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
movies_dataset.isnull().sum()

index                      0
budget                     0
genres                    28
homepage                3091
id                         0
keywords                 412
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
cast                      43
crew                       0
director                  30
dtype: int64

In [ ]:
# Replaceing the null values with null string
movies_dataset_selected_features = ["genres" ,"keywords", "tagline" , "cast" , "director" , "overview"]
print(movies_dataset_selected_features)

for movies_feature in movies_dataset_selected_features:
  movies_dataset[movies_feature] = movies_dataset[movies_feature].fillna('')


['genres', 'keywords', 'tagline', 'cast', 'director', 'overview']


In [ ]:
# after replace the null values with null string

movies_dataset.isnull().sum()

index                      0
budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   0
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                    0
title                      0
vote_average               0
vote_count                 0
cast                       0
crew                       0
director                   0
dtype: int64

In [ ]:
movies_dataset_combined_features = movies_dataset["genres"]+movies_dataset["keywords"]+movies_dataset["tagline"]+movies_dataset["cast"]+movies_dataset["director"]+movies_dataset["overview"]+movies_dataset["spoken_languages"]

In [ ]:
print(movies_dataset_combined_features)

0       Action Adventure Fantasy Science Fictioncultur...
1       Adventure Fantasy Actionocean drug abuse exoti...
2       Action Adventure Crimespy based on novel secre...
3       Action Crime Drama Thrillerdc comics crime fig...
4       Action Adventure Science Fictionbased on novel...
                              ...                        
4798    Action Crime Thrillerunited states\u2013mexico...
4799    Comedy RomanceA newlywed couple's honeymoon is...
4800    Comedy Drama Romance TV Moviedate love at firs...
4801    A New Yorker in ShanghaiDaniel Henney Eliza Co...
4802    Documentaryobsession camcorder crush dream gir...
Length: 4803, dtype: object


In [ ]:
movies_vectorizer = TfidfVectorizer()
# now coverting the text data into numerical values

In [ ]:
movies_dataset_feature_vectors = movies_vectorizer.fit_transform(movies_dataset_combined_features)

In [ ]:
print(movies_dataset_feature_vectors)

  (0, 41308)	0.08467576563325616
  (0, 13553)	0.08467576563325616
  (0, 13524)	0.08460928984916008
  (0, 13292)	0.025027099641710994
  (0, 27858)	0.04771196927912608
  (0, 13195)	0.025037544348003173
  (0, 21103)	0.04771196927912608
  (0, 7222)	0.15568663203464664
  (0, 1430)	0.11825047246962574
  (0, 1731)	0.051470085292528896
  (0, 31552)	0.16023623132059012
  (0, 1769)	0.029876590512831244
  (0, 29099)	0.15187837501142565
  (0, 15640)	0.1356360663360576
  (0, 4075)	0.09355287408825629
  (0, 40332)	0.1381049474994029
  (0, 3690)	0.09168473798820528
  (0, 5674)	0.05793317976009039
  (0, 26718)	0.10344620379222842
  (0, 41814)	0.14484611467454275
  (0, 28969)	0.0463706925542829
  (0, 27008)	0.14399392264522204
  (0, 40202)	0.029031509275766632
  (0, 11238)	0.17334953917522744
  (0, 21057)	0.038973462980564186
  :	:
  (4802, 43318)	0.08401265146239384
  (4802, 28901)	0.06257729544289954
  (4802, 44374)	0.06451279942997921
  (4802, 35920)	0.05364279309387087
  (4802, 18806)	0.08762025816

Cosine Similarity

In [ ]:
# getting the similarity scores using cosine similarity

movies_dataset_similarity = cosine_similarity(movies_dataset_feature_vectors)

In [ ]:
print(movies_dataset_similarity)

[[1.         0.04921925 0.05107401 ... 0.02785771 0.0346416  0.00925427]
 [0.04921925 1.         0.04719862 ... 0.04802261 0.03383259 0.01817058]
 [0.05107401 0.04719862 1.         ... 0.02950037 0.01670306 0.01882214]
 ...
 [0.02785771 0.04802261 0.02950037 ... 1.         0.04036208 0.0218979 ]
 [0.0346416  0.03383259 0.01670306 ... 0.04036208 1.         0.03549479]
 [0.00925427 0.01817058 0.01882214 ... 0.0218979  0.03549479 1.        ]]


In [ ]:
print(movies_dataset_similarity.shape)

(4803, 4803)


In [ ]:
# movie name from the user input

movie_name = input("Enter your favourite movie name : ")

Enter your favourite movie name : batman


In [ ]:
# creating a list with all the movie names given in the dataset

movies_dataset_list_of_all_titles = movies_dataset["title"].tolist()

print(movies_dataset_list_of_all_titles)



['Avatar', "Pirates of the Caribbean: At World's End", 'Spectre', 'The Dark Knight Rises', 'John Carter', 'Spider-Man 3', 'Tangled', 'Avengers: Age of Ultron', 'Harry Potter and the Half-Blood Prince', 'Batman v Superman: Dawn of Justice', 'Superman Returns', 'Quantum of Solace', "Pirates of the Caribbean: Dead Man's Chest", 'The Lone Ranger', 'Man of Steel', 'The Chronicles of Narnia: Prince Caspian', 'The Avengers', 'Pirates of the Caribbean: On Stranger Tides', 'Men in Black 3', 'The Hobbit: The Battle of the Five Armies', 'The Amazing Spider-Man', 'Robin Hood', 'The Hobbit: The Desolation of Smaug', 'The Golden Compass', 'King Kong', 'Titanic', 'Captain America: Civil War', 'Battleship', 'Jurassic World', 'Skyfall', 'Spider-Man 2', 'Iron Man 3', 'Alice in Wonderland', 'X-Men: The Last Stand', 'Monsters University', 'Transformers: Revenge of the Fallen', 'Transformers: Age of Extinction', 'Oz: The Great and Powerful', 'The Amazing Spider-Man 2', 'TRON: Legacy', 'Cars 2', 'Green Lant

In [ ]:
# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name, movies_dataset_list_of_all_titles)

print(find_close_match)

['Batman', 'Batman', 'Catwoman']


In [ ]:
close_match = find_close_match[0]

print(close_match)

Batman


In [ ]:
# finding the index of the movie with title

index_of_the_movie = movies_dataset[movies_dataset.title == close_match]["index"].values[0]

print(index_of_the_movie)

1359


In [ ]:
# getting the list of similar movies

similarity_score = list(enumerate(movies_dataset_similarity[index_of_the_movie]))

print(similarity_score)

[(0, 0.029010444913763464), (1, 0.04604923176460119), (2, 0.03783377112323018), (3, 0.19354999214743676), (4, 0.032852169344758), (5, 0.05223320797616247), (6, 0.02279388787515107), (7, 0.023882874347675352), (8, 0.06547060802064397), (9, 0.10248440850375072), (10, 0.0885612548631132), (11, 0.04109650324839434), (12, 0.034585049132416446), (13, 0.016618734775265962), (14, 0.07956780828826136), (15, 0.03103545632403446), (16, 0.04064344016289975), (17, 0.04627296361939403), (18, 0.04421121023479059), (19, 0.03533398423007057), (20, 0.04326370935228623), (21, 0.04654506304422275), (22, 0.01504618838147888), (23, 0.03361145243524399), (24, 0.02789255417448693), (25, 0.04830717879709008), (26, 0.03303559792829884), (27, 0.03163113428844987), (28, 0.006223452645107956), (29, 0.019019388460020208), (30, 0.07691072654610114), (31, 0.021333425609642024), (32, 0.030789199069110117), (33, 0.011276425357751075), (34, 0.010038563283178165), (35, 0.030191706649193798), (36, 0.052981536050863726), (

In [ ]:
len(similarity_score)

4803

In [ ]:
# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print(sorted_similar_movies)

[(1359, 0.9999999999999998), (210, 0.19991361720216466), (119, 0.19571194981391735), (3, 0.19354999214743676), (428, 0.18173450968293298), (65, 0.16400999867222507), (299, 0.15716250278192606), (3854, 0.1473363613230776), (9, 0.10248440850375072), (1477, 0.09386751277029626), (1469, 0.09268854392323592), (1390, 0.08899213252917602), (10, 0.0885612548631132), (4759, 0.08684543122444158), (1803, 0.08325358648827842), (2365, 0.0825455540244086), (72, 0.0823811782207107), (438, 0.0818714470182789), (870, 0.08135059963060393), (4558, 0.08011227649947984), (14, 0.07956780828826136), (782, 0.07874679114055615), (1664, 0.07837213854713841), (3047, 0.0774346527679465), (1247, 0.0770205072299357), (3600, 0.07691305625000186), (30, 0.07691072654610114), (1296, 0.07687643166219565), (79, 0.07677677449032153), (813, 0.07591896383199177), (2265, 0.07540588677571942), (1017, 0.07492987600313591), (4392, 0.07457313181219234), (2389, 0.07456327992066823), (2885, 0.07435033108506085), (1141, 0.074130703

In [ ]:
# print the name of similar movies based on the index

print("Movies suggested for you : \n")

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index = movies_dataset[movies_dataset.index==index]["title"].values[0]
  if(i<30):
    print(i, "_",title_from_index)
    i+=1

Movies suggested for you : 

1 _ Batman
2 _ Batman & Robin
3 _ Batman Begins
4 _ The Dark Knight Rises
5 _ Batman Returns
6 _ The Dark Knight
7 _ Batman Forever
8 _ Batman: The Dark Knight Returns, Part 2
9 _ Batman v Superman: Dawn of Justice
10 _ Reds
11 _ Chill Factor
12 _ Underworld: Rise of the Lycans
13 _ Superman Returns
14 _ The Image Revolution
15 _ Blood and Wine
16 _ Nine 1/2 Weeks
17 _ Suicide Squad
18 _ Something's Gotta Give
19 _ Superman II
20 _ Alleluia! The Devil's Carnival
21 _ Man of Steel
22 _ The Spirit
23 _ Dead Man Down
24 _ Big Eyes
25 _ City By The Sea
26 _ Halloween 4: The Return of Michael Myers
27 _ Spider-Man 2
28 _ Superman III
29 _ Iron Man 2


Movies Recommendation System

In [ ]:
movie_name = input("Enter your favourite movie name : ")

movies_dataset_list_of_all_titles = movies_dataset["title"].tolist()

find_close_match = difflib.get_close_matches(movie_name, movies_dataset_list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie = movies_dataset[movies_dataset.title == close_match]["index"].values[0]

similarity_score = list(enumerate(movies_dataset_similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print("Movies suggested for you : \n")

i = 1

for movie in sorted_similar_movies:

  index = movie[0]
  title_from_index = movies_dataset[movies_dataset.index==index]["title"].values[0]
  if(i<30):
    print(i, "_",title_from_index)
    i+=1

Enter your favourite movie name : avengers
Movies suggested for you : 

1 _ The Avengers
2 _ Avengers: Age of Ultron
3 _ Captain America: The Winter Soldier
4 _ Iron Man 2
5 _ The Incredible Hulk
6 _ X-Men
7 _ X-Men: Apocalypse
8 _ Captain America: Civil War
9 _ Thor: The Dark World
10 _ The Helix... Loaded
11 _ Thor
12 _ X-Men: The Last Stand
13 _ X-Men: Days of Future Past
14 _ X2
15 _ Ant-Man
16 _ Man of Steel
17 _ Deadpool
18 _ The Losers
19 _ The Amazing Spider-Man 2
20 _ Snowpiercer
21 _ Superman II
22 _ Iron Man 3
23 _ A Scanner Darkly
24 _ Kick-Ass
25 _ Guardians of the Galaxy
26 _ Iron Man
27 _ Zodiac
28 _ Captain America: The First Avenger
29 _ Thank You for Smoking
